# Generated by Django 2.2.5 on 2020-11-17 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversaion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messsages', to='conversations.Conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messsages', to=settings.AUTH_USER_MODEL),
        ),
    ]
