# Generated by Django 2.2.5 on 2020-11-17 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20201117_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participates',
            field=models.ManyToManyField(blank=True, related_name='conversation', to=settings.AUTH_USER_MODEL),
        ),
    ]
